-- MySQL Script generated by MySQL Workbench
-- Wed Apr  4 17:22:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chat_melt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chat_melt` ;

-- -----------------------------------------------------
-- Schema chat_melt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat_melt` DEFAULT CHARACTER SET utf8 ;
USE `chat_melt` ;

-- -----------------------------------------------------
-- Table `chat_melt`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat_melt`.`users` ;

CREATE TABLE IF NOT EXISTS `chat_melt`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `online` TINYINT(1) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_melt`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat_melt`.`messages` ;

CREATE TABLE IF NOT EXISTS `chat_melt`.`messages` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `msg_time` TIMESTAMP NULL,
  PRIMARY KEY (`id_message`),
  INDEX `fk_messages_users_idx` (`username` ASC),
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`username`)
    REFERENCES `chat_melt`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
